services:
  - type: web
    name: gamingboxd
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.3
      - key: DATABASE_URL
        sync: false
      - key: STEAM_API_KEY
        sync: false
